from pathlib import Path
import sys

# ---------------------------------------------------
# Add project root
# ---------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------
# Imports
# ---------------------------------------------------
import streamlit as st
import pandas as pd

from dashboard.components.sidebar import render_sidebar
from dashboard.components.metrics import display_metrics
from dashboard.components.charts import (
    fraud_distribution_chart,
    fraud_probability_histogram,
    amount_vs_probability,
    top_risky_transactions,
)

# ---------------------------------------------------
# Page Configuration
# ---------------------------------------------------
st.set_page_config(
    page_title="Dashboard",
    page_icon="📊",
    layout="wide",
)

render_sidebar()

# ---------------------------------------------------
# Title
# ---------------------------------------------------
st.title("📊 Fraud Analytics Dashboard")

st.markdown(
    """
This dashboard provides an overview of fraud predictions generated by the
SentinelAI machine learning model.
"""
)

st.divider()

# ---------------------------------------------------
# Upload Prediction CSV
# ---------------------------------------------------
uploaded_file = st.file_uploader(
    "Upload prediction CSV",
    type=["csv"],
)

if uploaded_file is None:

    st.info("👆 Upload a prediction CSV to view analytics.")

    st.stop()

# ---------------------------------------------------
# Read Data
# ---------------------------------------------------
try:
    df = pd.read_csv(uploaded_file)

except Exception as e:
    st.error(f"Unable to read CSV: {e}")
    st.stop()

# ---------------------------------------------------
# Validate Required Columns
# ---------------------------------------------------
required_columns = [
    "Prediction",
    "Fraud Probability",
    "Prediction Label",
    "Amount",
]

missing = [c for c in required_columns if c not in df.columns]

if missing:
    st.error(
        f"Missing required columns: {', '.join(missing)}"
    )
    st.stop()

# ---------------------------------------------------
# Metrics
# ---------------------------------------------------
total = len(df)

fraud = (df["Prediction"] == 1).sum()

legitimate = (df["Prediction"] == 0).sum()

fraud_rate = fraud / total * 100

display_metrics(
    total,
    fraud,
    legitimate,
    fraud_rate,
)

st.divider()

# ---------------------------------------------------
# Charts
# ---------------------------------------------------
left, right = st.columns(2)

with left:
    fraud_distribution_chart(df)

with right:
    fraud_probability_histogram(df)

st.divider()

amount_vs_probability(df)

st.divider()

top_risky_transactions(df)

st.divider()

# ---------------------------------------------------
# Raw Dataset
# ---------------------------------------------------
with st.expander("View Prediction Dataset"):

    st.dataframe(
        df,
        use_container_width=True,
    )